# Generated by Django 2.2.1 on 2019-11-24 04:23

from django.db import migrations, models
import django.db.models.deletion
import scraper.models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='title',
        ),
        migrations.AddField(
            model_name='instructor',
            name='case_id',
            field=models.CharField(default='aaa000', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='dept',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='scraper.Department'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(default='aaa000', on_delete=django.db.models.deletion.SET_DEFAULT, to='scraper.Instructor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='units',
            field=models.IntegerField(validators=[scraper.models.validate_credit_hours]),
        ),
        migrations.AlterField(
            model_name='department',
            name='school',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='scraper.School'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='dept',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='scraper.Department'),
        ),
    ]
