# Generated by Django 2.2.1 on 2019-11-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='url',
            field=models.CharField(default='https://case.edu/bulletin/', max_length=100),
        ),
    ]
