# Generated by Django 2.2.1 on 2019-11-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20191126_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='url',
            field=models.CharField(default='https://case.edu/bulletin/', max_length=100),
        ),
    ]
