# Generated by Django 2.2.1 on 2019-11-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20191124_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default='------', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(default='------', max_length=50, primary_key=True, serialize=False),
        ),
    ]
