# Generated by Django 2.2.1 on 2019-11-24 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20191124_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='dept',
            field=models.ForeignKey(default='DEFAULT', on_delete=django.db.models.deletion.SET_DEFAULT, to='scraper.Department'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(default='DEFAULT', on_delete=django.db.models.deletion.SET_DEFAULT, to='scraper.Instructor'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default='DEFAULT', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='school',
            field=models.ForeignKey(default='DEFAULT', on_delete=django.db.models.deletion.SET_DEFAULT, to='scraper.School'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='case_id',
            field=models.CharField(default='DEFAULT', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='dept',
            field=models.ForeignKey(default='DEFAULT', on_delete=django.db.models.deletion.SET_DEFAULT, to='scraper.Department'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(default='DEFAULT', max_length=50, primary_key=True, serialize=False),
        ),
    ]
