# Generated by Django 2.2.1 on 2019-12-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_review_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created time'),
        ),
    ]
