# Generated by Django 2.2.1 on 2019-12-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_auto_20191203_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='watched_classes',
            field=models.ManyToManyField(blank=True, null=True, related_name='watched_courses', to='scraper.Course'),
        ),
    ]
